# Generated by Django 4.2.3 on 2023-12-08 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productormapp', '0002_alter_product_category_alter_product_desc_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
